# Generated by Django 6.0.1 on 2026-01-31 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ports", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="port",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="port",
            name="avg_wait_time",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="port",
            name="capacity",
            field=models.CharField(default="Medium", max_length=20),
        ),
        migrations.AddField(
            model_name="port",
            name="code",
            field=models.CharField(default="UNKNOWN", max_length=50),
        ),
        migrations.AddField(
            model_name="port",
            name="congestion_score",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="port",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="port",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="port",
            name="port_type",
            field=models.CharField(default="container", max_length=50),
        ),
        migrations.AddField(
            model_name="port",
            name="region",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="port",
            name="timezone",
            field=models.CharField(default="UTC", max_length=50),
        ),
        migrations.AddField(
            model_name="port",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="port",
            name="vessels_in_port",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="port",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterModelTable(
            name="port",
            table="ports_port",
        ),
    ]
