# Generated by Django 6.0.1 on 2026-02-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ports", "0002_alter_port_options_port_avg_wait_time_port_capacity_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="port",
            options={},
        ),
        migrations.RemoveField(
            model_name="port",
            name="avg_wait_time",
        ),
        migrations.RemoveField(
            model_name="port",
            name="capacity",
        ),
        migrations.RemoveField(
            model_name="port",
            name="code",
        ),
        migrations.RemoveField(
            model_name="port",
            name="congestion_score",
        ),
        migrations.RemoveField(
            model_name="port",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="port",
            name="description",
        ),
        migrations.RemoveField(
            model_name="port",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="port",
            name="port_type",
        ),
        migrations.RemoveField(
            model_name="port",
            name="region",
        ),
        migrations.RemoveField(
            model_name="port",
            name="timezone",
        ),
        migrations.RemoveField(
            model_name="port",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="port",
            name="vessels_in_port",
        ),
        migrations.AddField(
            model_name="port",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="port",
            name="source",
            field=models.CharField(default="WPI", max_length=50),
        ),
        migrations.AlterField(
            model_name="port",
            name="country",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="port",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterModelTable(
            name="port",
            table=None,
        ),
    ]
