# Generated by Django 6.0.1 on 2026-01-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vessel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("imo_number", models.CharField(max_length=20, unique=True)),
                (
                    "vessel_type",
                    models.CharField(
                        choices=[
                            ("Cargo", "Cargo"),
                            ("Tanker", "Tanker"),
                            ("Passenger", "Passenger"),
                        ],
                        max_length=20,
                    ),
                ),
                ("flag", models.CharField(max_length=50)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("speed", models.FloatField(help_text="Speed in knots")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Moving", "Moving"),
                            ("Anchored", "Anchored"),
                            ("Docked", "Docked"),
                        ],
                        max_length=20,
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
