# Generated by Django 5.2.10 on 2026-01-27 10:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vessels", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VesselPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                (
                    "speed",
                    models.FloatField(
                        blank=True, help_text="Speed in knots", null=True
                    ),
                ),
                (
                    "course",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Course in degrees",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "heading",
                    models.IntegerField(
                        blank=True, help_text="Heading in degrees", null=True
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("data_source", models.CharField(default="aisstream", max_length=50)),
            ],
            options={
                "verbose_name": "Vessel Position",
                "verbose_name_plural": "Vessel Positions",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AlterModelOptions(
            name="vessel",
            options={"ordering": ["-last_updated"]},
        ),
        migrations.AddField(
            model_name="vessel",
            name="callsign",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="vessel",
            name="course",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Course Over Ground (degrees)",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="vessel",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vessel",
            name="data_source",
            field=models.CharField(
                default="manual",
                help_text="Data source: aisstream, manual, etc",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="vessel",
            name="destination",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="vessel",
            name="draft",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Draft in meters",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="vessel",
            name="eta",
            field=models.DateTimeField(
                blank=True, help_text="Estimated Time of Arrival", null=True
            ),
        ),
        migrations.AddField(
            model_name="vessel",
            name="gross_tonnage",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vessel",
            name="heading",
            field=models.IntegerField(
                blank=True, help_text="True heading (degrees)", null=True
            ),
        ),
        migrations.AddField(
            model_name="vessel",
            name="imo",
            field=models.CharField(
                blank=True,
                help_text="IMO number (alternate field)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="vessel",
            name="last_position_update",
            field=models.DateTimeField(
                blank=True, help_text="Last AIS position update", null=True
            ),
        ),
        migrations.AddField(
            model_name="vessel",
            name="length",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Length in meters",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="vessel",
            name="mmsi",
            field=models.CharField(
                blank=True,
                help_text="Maritime Mobile Service Identity",
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="vessel",
            name="nav_status",
            field=models.IntegerField(
                blank=True, help_text="AIS navigation status code", null=True
            ),
        ),
        migrations.AddField(
            model_name="vessel",
            name="nav_status_text",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="vessel",
            name="type",
            field=models.CharField(
                blank=True, help_text="Simplified vessel type", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="vessel",
            name="type_code",
            field=models.IntegerField(
                blank=True, help_text="AIS ship type code", null=True
            ),
        ),
        migrations.AddField(
            model_name="vessel",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="vessel",
            name="width",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Width in meters",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="vessel",
            name="status",
            field=models.CharField(
                choices=[
                    ("Moving", "Moving"),
                    ("Anchored", "Anchored"),
                    ("Docked", "Docked"),
                    ("active", "Active"),
                    ("underway", "Underway"),
                    ("moored", "Moored"),
                    ("inactive", "Inactive"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="vessel",
            name="vessel_type",
            field=models.CharField(
                choices=[
                    ("Cargo", "Cargo"),
                    ("Tanker", "Tanker"),
                    ("Passenger", "Passenger"),
                    ("Fishing", "Fishing"),
                    ("Sailing", "Sailing"),
                    ("Tug", "Tug"),
                    ("Other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="vessel",
            index=models.Index(
                fields=["imo_number"], name="vessels_ves_imo_num_1c2106_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vessel",
            index=models.Index(fields=["mmsi"], name="vessels_ves_mmsi_d9a636_idx"),
        ),
        migrations.AddIndex(
            model_name="vessel",
            index=models.Index(
                fields=["-last_position_update"], name="vessels_ves_last_po_3e498c_idx"
            ),
        ),
        migrations.AddField(
            model_name="vesselposition",
            name="vessel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="positions",
                to="vessels.vessel",
            ),
        ),
        migrations.AddIndex(
            model_name="vesselposition",
            index=models.Index(
                fields=["vessel", "-timestamp"], name="vessels_ves_vessel__2ffb7b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vesselposition",
            index=models.Index(
                fields=["-timestamp"], name="vessels_ves_timesta_a1a206_idx"
            ),
        ),
    ]
