# Generated by Django 6.0.1 on 2026-01-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "vessels",
            "0002_vesselposition_alter_vessel_options_vessel_callsign_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="vessel",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vessel",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vessel",
            name="speed",
            field=models.FloatField(blank=True, help_text="Speed in knots", null=True),
        ),
    ]
