# Generated by Django 6.0.1 on 2026-01-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vessels", "0003_alter_vessel_latitude_alter_vessel_longitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vessel",
            name="flag",
            field=models.CharField(default="Unknown", max_length=50),
        ),
        migrations.AlterField(
            model_name="vessel",
            name="imo_number",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="vessel",
            name="mmsi",
            field=models.CharField(
                default=1,
                help_text="Maritime Mobile Service Identity",
                max_length=20,
                unique=True,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="vessel",
            name="status",
            field=models.CharField(
                choices=[
                    ("Moving", "Moving"),
                    ("Anchored", "Anchored"),
                    ("Docked", "Docked"),
                    ("active", "Active"),
                    ("underway", "Underway"),
                    ("moored", "Moored"),
                    ("inactive", "Inactive"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="vessel",
            name="vessel_type",
            field=models.CharField(
                choices=[
                    ("Cargo", "Cargo"),
                    ("Tanker", "Tanker"),
                    ("Passenger", "Passenger"),
                    ("Fishing", "Fishing"),
                    ("Sailing", "Sailing"),
                    ("Tug", "Tug"),
                    ("Other", "Other"),
                ],
                default="Other",
                max_length=20,
            ),
        ),
    ]
