# Generated by Django 6.0.1 on 2026-02-01 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vessels", "0004_alter_vessel_flag_alter_vessel_imo_number_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="vessel",
            index=models.Index(
                fields=["-last_updated"], name="vessels_ves_last_up_9c26a9_idx"
            ),
        ),
    ]
