# Generated by Django 6.0.1 on 2026-02-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vessels", "0005_vessel_vessels_ves_last_up_9c26a9_idx"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="vessel",
            name="vessels_ves_last_up_9c26a9_idx",
        ),
        migrations.AddField(
            model_name="vessel",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="vessel",
            name="flag",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
