# Generated by Django 6.0.1 on 2026-02-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vessels", "0006_remove_vessel_vessels_ves_last_up_9c26a9_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vesselposition",
            name="latitude",
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name="vesselposition",
            name="longitude",
            field=models.FloatField(db_index=True),
        ),
    ]
