# Generated by Django 6.0.1 on 2026-01-22 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ports", "0001_initial"),
        ("vessels", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Voyage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("departure_time", models.DateTimeField()),
                ("arrival_time", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Planned", "Planned"),
                            ("Ongoing", "Ongoing"),
                            ("Completed", "Completed"),
                        ],
                        default="Planned",
                        max_length=20,
                    ),
                ),
                (
                    "destination_port",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arrivals",
                        to="ports.port",
                    ),
                ),
                (
                    "origin_port",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departures",
                        to="ports.port",
                    ),
                ),
                (
                    "vessel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vessels.vessel"
                    ),
                ),
            ],
        ),
    ]
