# Generated by Django 6.0.1 on 2026-01-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voyages", "0002_alter_voyage_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voyage",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
